### ISSUE TITLE
Crash after `upgrade` <TAB>

### ISSUE THREAD

**Issue by zawadaa** [poldek-pm/poldek#23]
```
poldek:/all-avail> upgrade Something wrong, something not quite right with 0.42.2 (stable)
Assertion 'len > 0' failed, n_hash_new.c:139
Please report this bug to: https://github.com/poldek-pm/poldek/issues/new

Przerwane (zrzut pamięci)
```

**Comment by zawadaa** [comment]
some update:
`reload` subcommand in poldek doesn't work. poldek can't read rpm database.
Some gdb output:

> (gdb) bt
#0  0x00007ffff7d271ec in ?? () from /lib64/libc.so.6
#1  0x00007ffff7cd6dd6 in raise () from /lib64/libc.so.6
#2  0x00007ffff7cbf835 in abort () from /lib64/libc.so.6
#3  0x00007ffff7f00611 in ?? () from /usr/lib64/libpoldek.so.3
#4  0x00007ffff7ee6ff8 in n_hash_compute_hash () from /usr/lib64/libtrurl.so.0
#5  0x00007ffff7ee6a2f in n_hash_get_ex () from /usr/lib64/libtrurl.so.0
#6  0x00007ffff7ee6a81 in n_hash_get () from /usr/lib64/libtrurl.so.0
#7  0x00007ffff7f1efea in ?? () from /usr/lib64/libpoldek.so.3
#8  0x00007ffff7f3b31f in ?? () from /usr/lib64/libpoldek.so.3
#9  0x00007ffff7f3b5f5 in ?? () from /usr/lib64/libpoldek.so.3
#10 0x00007ffff7f32c70 in pkgdir_load () from /usr/lib64/libpoldek.so.3
#11 0x00007ffff7f53e86 in ?? () from /usr/lib64/libpoldek.so.3
#12 0x00007ffff7f50c13 in pkgdb_to_pkgdir () from /usr/lib64/libpoldek.so.3
#13 0x00007ffff7f855cd in ?? () from /usr/lib64/libpoclidek.so.1
#14 0x00007ffff7f85840 in poclidek.load_installed () from /usr/lib64/libpoclidek.so.1
#15 0x00007ffff7f803e5 in poclidek_load_packages () from /usr/lib64/libpoclidek.so.1
#16 0x00007ffff7f8fb97 in ?? () from /usr/lib64/libpoclidek.so.1
#17 0x00007ffff7f7fc7c in ?? () from /usr/lib64/libpoclidek.so.1
#18 0x00007ffff7f805e7 in ?? () from /usr/lib64/libpoclidek.so.1
#19 0x0000000000404e6c in poclidek_shell (cctx=0x41b8e0) at shell.c:591
#20 0x0000000000403980 in run_ipoldek (cctx=<optimized out>) at main.c:650
#21 main (argc=1, argv=0x7fffffffdee8) at main.c:713

**Comment by mistoo** [comment]
I'm closing this as probably outdated issue, reopen if it still happening.

**Comment by zawadaa** [comment]
External RPM was causing that error.
One tag in rpm definition was empty/null - IIRC.
Closed.
